---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-sc
# provisioner: kubernetes.io/no-provisioner
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: jenkins-sc
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pv-claim
#   namespace: jenkins
# spec:
#   storageClassName: jenkins-sc
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
